### ISSUE TITLE
Lookup by enum member / label

### ISSUE THREAD

**Issue by mjwills** [xin9le/FastEnum#10]
`GetEnumMemberValue` and `GetLabel` are fantastic for mapping from an enum value to a string.

Is there any means to do it the other way around (i.e. map from the enum member / label string _back to the enum value_)?

**Comment by xin9le** [comment]
Sorry for the late reply, and thanks for nice suggestion.

At this time, FastEnum doesn't provide these mapping features. This's because I have never felt the need for these in the past.

I thought about these again, the string value specified in the attribute can be duplicated, so it isn't possible to uniquely determine the enum value. Therefore, I am concerned that these features may not be useful.

```cs
// If specified "Bar", which should I select?

public enum Foo
{
    [Label("Bar")]
    A = 1,

    [Label("Bar")]
    B = 2,
}
```
